CREATE TABLE IF NOT EXISTS post_likes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    postId INT NOT NULL,
    userId INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_id_posts_likes FOREIGN KEY (userId) REFERENCES users(id),
    CONSTRAINT fk_post_id_post_likes FOREIGN KEY (postId) REFERENCES posts(id)
)